[book]
authors = ["Florian Kellner", "Linus Szillat"]
language = "en"
title = "BSL-Tools" 

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/se-tuebingen/bsl-tools"
git-repository-icon = "fa-github"
additional-js =["bsl_tools.js"]